apiVersion: v2
name: paigo-prometheus-sample-chart
description: Helm configuration for prometheus to work with Paigo
keywords:
- paigo
- billing
- kubernetes
type: application
version: 1.0.0
appVersion: '1.0.0'
home: https://github.com/paigo-tech/paigo-prometheus-sample
sources:
    - https://github.com/paigo-tech/paigo-prometheus-sample
maintainers:
    - name: danielwasserlauf
      email: daniel.wasserlauf@paigo.tech
