apiVersion: v1
data:
    clientSecret: '{{ .Values.clientSecretKey | b64enc }}'
kind: Secret
metadata:
    name: '{{ .Values.clientSecretName }}'
    namespace: '{{ .Values.namespace }}'
type: Opaque
